### ISSUE TITLE
Symbol not found with NanCallback

### ISSUE THREAD

**Issue by mmalecki** [nodejs/nan#32]
Hi,

I'm trying to use nan for sophia binary addon. I use `NanCallback` with async workers and have been running into the following crash:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN6sophia3SetEPvPKvmS2_mP11NanCallback
  Referenced from: /Users/maciej/dev/js/sophia/build/Debug/sophia.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN6sophia3SetEPvPKvmS2_mP11NanCallback
  Referenced from: /Users/maciej/dev/js/sophia/build/Debug/sophia.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

Piece of code which (I think) is responsible for that:

``` cpp
    sophia::Set(
      wrap->db,
      key,
      strlen(key),
      value,
      strlen(value),
      new NanCallback(callback)
    );
    NanReturnUndefined();
```

Which is weird, since I use the exact same invocation of `NanCallback` somewhere else in the same file and it works.

Full code is [here](https://github.com/mmalecki/node-sophia/tree/put), the piece of code in question is [here](https://github.com/mmalecki/node-sophia/blob/put/src/database_wrap.cc#L77-L86).

Way to reproduce (works on node 0.10):

``` sh
git clone https://github.com/mmalecki/node-sophia.git
cd node-sophia
git checkout put
npm i
node test/simple-test.js
```
