### ISSUE TITLE
`fatal error: core.h: No such file or directory` breaks build against node 10.2.0

### ISSUE THREAD

**Issue by mkrufky** [nodejs/nan#776]
node 10.1.0 was fine, but 10.2.0 introduced this new fatal error:
```
mk@vujade:~/git/nan$ npm run rebuild-tests 

> nan@2.10.0 rebuild-tests /home/mk/git/nan
> node-gyp rebuild --msvs_version=2015 --directory test

make: Entering directory '/home/mk/git/nan/test/build'
  CXX(target) Release/obj.target/accessors/cpp/accessors.o
In file included from ../../nan.h:51:0,
                 from ../cpp/accessors.cpp:9:
/home/mk/.node-gyp/10.2.0/include/node/node.h:53:10: fatal error: core.h: No such file or directory
 #include "core.h"  // NOLINT(build/include_order)
          ^~~~~~~~
compilation terminated.
```

I first noticed this in CI:
https://travis-ci.org/mkrufky/node-dvbtee/jobs/382993499

...and then I was able to easily reproduce it locally after upgrading node from v10.1.0 to v10.2.0

Oops, this is a node bug, and not _NAN_'s issue:  https://github.com/nodejs/node/issues/20921

Will likely end up closing this soon.

**Comment by mkrufky** [comment]
Closing this now -- a fix for it landed upstream in nodejs/node@3f4caec. A 10.2.1 release with that fix should follow shortly.  No changes to _NAN_ or any native modules are necessary.
