### ISSUE TITLE
I'm seeing parameter mismatches for uv_async_cb between node v0.11.13 and and node v0.10.28

### ISSUE THREAD

**Issue by chanced** [nodejs/nan#151]
First off, I'm beyond rusty on C++ but I need to get [fsevents](https://github.com/pipobscure/fsevents) working on Node 0.11.13. As such, I'm muddling my way through it. 

One of the errors I ran into initially, while using Node v0.11.13 was a mismatch on `uv_async_init` from this code:

``` c++
// source: https://github.com/pipobscure/fsevents/blob/master/src/async.cc

void async_propagate(uv_async_t *async, int status) {
  if (!async->data) return;
  FSEvents *fse = (FSEvents *)async->data;
  CFIndex idx, cnt;
  fse_event *event;
  char pathbuf[1024];
  const char *pathptr = NULL;
  fse->lock();
  cnt = CFArrayGetCount(fse->events);
  for (idx=0; idx<cnt; idx++) {
    event = (fse_event *)CFArrayGetValueAtIndex(fse->events, idx);
    pathptr = CFStringGetCStringPtr(event->path, kCFStringEncodingUTF8);
    if (!pathptr) CFStringGetCString(event->path, pathbuf, 1024, kCFStringEncodingUTF8);
    fse->emitEvent(pathptr ? pathptr : pathbuf, event->flags, event->id);
  }
  if (cnt>0) CFArrayRemoveAllValues(fse->events);
  fse->unlock();
}

void FSEvents::asyncStart() {
  if (async.data == this) return;
  async.data = this;
  uv_async_init(uv_default_loop(), &async, &async_propagate);
}
```

Which was throwing this error:

```
../src/async.cc:29:3: error: no matching function for call to 'uv_async_init'
  uv_async_init(uv_default_loop(), &async, &async_propagate);
  ^~~~~~~~~~~~~
/Users/chance/.node-gyp/0.11.13/deps/uv/include/uv.h:1355:15: note: candidate function not viable: no known conversion from 'void (*)(uv_async_t *, int)' to 'uv_async_cb' (aka 'void (*)(uv_async_t *)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*,
```

I removed the `status` param and it compiled.

``` c++
// source: https://github.com/chanced/fsevents/blob/master/src/async.cc

void async_propagate(uv_async_t *async) {
  if (!async->data) return;
  FSEvents *fse = (FSEvents *)async->data;
  CFIndex idx, cnt;
  fse_event *event;
  char pathbuf[1024];
  const char *pathptr = NULL;
  fse->lock();
  cnt = CFArrayGetCount(fse->events);
  for (idx=0; idx<cnt; idx++) {
    event = (fse_event *)CFArrayGetValueAtIndex(fse->events, idx);
    pathptr = CFStringGetCStringPtr(event->path, kCFStringEncodingUTF8);
    if (!pathptr) CFStringGetCString(event->path, pathbuf, 1024, kCFStringEncodingUTF8);
    fse->emitEvent(pathptr ? pathptr : pathbuf, event->flags, event->id);
  }
  if (cnt>0) CFArrayRemoveAllValues(fse->events);
  fse->unlock();
}

void FSEvents::asyncStart() {
  if (async.data == this) return;
  async.data = this;
  uv_async_init(uv_default_loop(), &async, async_propagate);
}
```

But now I'm getting the following error in Node v0.10.28:

```
../src/async.cc:29:3: error: no matching function for call to 'uv_async_init'
  uv_async_init(uv_default_loop(), &async, async_propagate);
  ^~~~~~~~~~~~~
/Users/chance/.node-gyp/0.10.28/deps/uv/include/uv.h:1192:15: note: candidate function not viable: no known conversion from
      'void (uv_async_t *)' to 'uv_async_cb' (aka 'void (*)(uv_async_t *, int)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*, uv_async_t* async,
              ^
```
