### ISSUE TITLE
WriteUtf8  does not take 5 arguments

### ISSUE THREAD

**Issue by Sneezry** [nodejs/nan#832]
Hi, I have no idea if I made some mistake. But I cannot rebuild nan with electron 3.0.10 (with node 10.2.0).

With command below to rebuild:

```
node-gyp rebuild --target=3.0.10 --arch=x64 --dist-url=https://atom.io/download/electron
```

The raw error I got is

```
C:\Users\...\node_modules\nan\nan.h(1081): error C2660: 'v8::String
::WriteUtf8': function does not take 5 arguments (compiling source file ..\src\combined.cpp) [C:\...\xxx.vcxproj]
```

I find that the latest nan will call `WriteUtf8` with 5 arguments if node version is larger than 10

https://github.com/nodejs/nan/blob/55923c824e4c148b127faec9b57d5b914f6a9ab9/nan.h#L1081

However, `WriteUtf8` only accepts 4 arguments in node 10

https://v8docs.nodesource.com/node-10.6/d2/db3/classv8_1_1_string.html#a99aec0d3b418feca1f2a2ba79416c60b

Any ideas? Thanks.

**Comment by Flarna** [comment]
The 4 param version has been deprecated in v8 in favor of the 5 param version and this has been backported to node 10 (see https://github.com/nodejs/node/pull/22531). Therefore the linked v8 docs don't match to the actual variant of v8 used by node.

See https://github.com/nodejs/node/blob/4128793a150dbcc63e03738ddd30f1768608aa11/deps/v8/include/v8.h#L2656

I assume that the same did not happen in electron and as a result some ifdefs are wrong in this setup.

**Comment by Flarna** [comment]
Actually it seems that the backport of the v8 change was done with Node 10.10.0. Therefore if someone uses Nan 2.12.0 with Node 10.0.0 till 10.9.0 build will fail.

**Comment by Flarna** [comment]
Caused by #825 - seems it's a decision between build errors and deprecation warnings.

**Comment by Flarna** [comment]
@amb26 I guess you mean compiling electron with NodeJs 10.10.0. Or some native node extension?

**Comment by refack** [comment]
@Flarna following your suggestion from https://github.com/mapbox/node-sqlite3/pull/1093#pullrequestreview-185457481 I got this situation:
* `nan@2.11.1` in node-sqlite3 on `NODE_VERSION="6" ELECTRON_VERSION="3.0.6"` compiles:
  https://travis-ci.org/mapbox/node-sqlite3/jobs/468473910

* `nan@2.12.0` in node-sqlite3 on `NODE_VERSION="6" ELECTRON_VERSION="3.0.6"` fails:
  https://travis-ci.org/mapbox/node-sqlite3/jobs/468884290

**Comment by bnoordhuis** [comment]
I'll put up a PR with a fix shortly.

**Comment by refack** [comment]
Using `sqlite3` as a canary with https://github.com/node4good/node-sqlite3/commit/62fa3c703bfa8e4421c0e33a24cbc9c5d736354c
https://travis-ci.com/node4good/node-sqlite3/jobs/165649311

**Comment by GU5TAF** [comment]
For anyone like myself who's just trying to get their app to build whilst waiting for #833 to land.
If you're using yarn you can add `nan` to the `resolutions` field in your `package.json`, like so:
```
