### ISSUE TITLE
Can't set `target` for `NanCallback->Call`

### ISSUE THREAD

**Issue by xzyfer** [nodejs/nan#362]
https://github.com/nodejs/nan/pull/275 introduced an optional `target` parameter for `NanCallback->Call`. This parameter (I believe) allows you to set the context for the callback i.e. this.

However not matter what I do the `this` value in my JavaScript callback is always the default `Global` context. I would expect the following to make foo available on this in my JavaScript callback.

```cpp
Local<Object> target = NanNew<Object>();
target->Set(NanNew<String>("foo"), NanNew<String>("bar"));
myNanCallback->Call(target, argv_v8.size(), &argv_v8[0]);
```

Is this a bug, or am I misunderstanding `target`?

**Comment by bnoordhuis** [comment]
I looked at the code and I don't see anything that is obviously wrong.  I added a regression test in #363 and that's passing for me as well (with io.js at least.)

**Comment by kkoopa** [comment]
Instead of passing `&argv_v8[0]`, you could just do `argv_v8`, but these are equivalent statements. Don't know why it does not work for you, tests pass here. Can you make a reproducible failing test?

**Comment by xzyfer** [comment]
Looking into this now. For what it's worth the change you suggested causes an error

```
../src/callback_bridge.h:139:37: error: no matching member function for call to 'Call'
    NanNew<Value>(bridge->callback->Call(context, argv_v8.size(), argv_v8));
                  ~~~~~~~~~~~~~~~~~~^~~~
```

Using iojs v2.0.0.

**Comment by kkoopa** [comment]
I was under the assumption that argv_v8 was an array of `Handle<Value>`.

**Comment by xzyfer** [comment]
In our case `argv_v8` is a `std::vector<Handle<Value>>`.

**Comment by xzyfer** [comment]
I'll try to boil down to a reduced test case. It's currently deep inside node-sass.

**Comment by kkoopa** [comment]
@xzyfer What's the status on this?

**Comment by xzyfer** [comment]
This is still an issue. I'm trying create a test case. 
I looked at the regression test you added. As far as I can tell you've simply asserting the code is valid, not that it produces the intended result. Am I missing something?

**Comment by mathiask88** [comment]
I did a small test on this with iojs 2.1.0/NAN 1.8.4
```c++
#include <node.h>
#include <nan.h>

namespace test {

  NAN_METHOD(test) {
    NanCallback cb(args[0].As<v8::Function>());
    v8::Handle<v8::Value> argv[1];

    v8::Local<v8::Object> target = NanNew<v8::Object>();
    target->Set(NanNew<v8::String>("foo"), NanNew<v8::String>("bar"));

    argv[0] = NanNew<v8::String>("par1");
    
    cb.Call(target, 1, argv);
  }

  void init(v8::Local<v8::Object> exports) {
    NODE_SET_METHOD(exports, "test", test);
  }

  NODE_MODULE(addon, init)

}  // namespace test
```
```javascript
var test = require('./build/Release/test.node');

test.test(function(par){
  console.log(this, par);
})
```
The result is the expected `{ foo: 'bar' } 'par1'`.

**Comment by kkoopa** [comment]
@xzyfer You are missing something. The test clearly tests functional correctness.

**Comment by xzyfer** [comment]
@kkoopa I expect you're correct.
