### ISSUE TITLE
1.9 broke my call to NanThrowError

### ISSUE THREAD

**Issue by LinusU** [nodejs/nan#390]
LinusU/fs-xattr#8

The following code works in `1.8.x` but not in `1.9`.

```c++
void ThrowExceptionErrno(int e) {

  Local<Object> err = v8::Exception::Error(NanNew(errorDescriptionForGet(e)))->ToObject();
  err->Set(NanNew("errno"), NanNew<Integer>(e));
  err->Set(NanNew("code"), NanNew(errorCode(e)));

  NanThrowError(err);
}
```

This is the error:

```text
In file included from ../src/xattr.cc:21:
../src/error.cc:109:3: error: call to 'NanThrowError' is ambiguous
  NanThrowError(err);
  ^~~~~~~~~~~~~
../node_modules/nan/nan.h:711:3: note: candidate function
  X(Error)
  ^
../node_modules/nan/nan.h:705:21: note: expanded from macro 'X'
    NAN_INLINE void NanThrow ## NAME(v8::Handle<v8::String> errmsg) {          \
                    ^
<scratch space>:93:1: note: expanded from here
NanThrowError
^
../node_modules/nan/nan.h:719:19: note: candidate function
  NAN_INLINE void NanThrowError(v8::Handle<v8::Value> error) {
                  ^
```

I think that maybe this is because of #322

**Comment by LinusU** [comment]
This code doesn't work as well:

```c++
NanThrowError(NanErrnoException(errno));
```

**Comment by LinusU** [comment]
The workaround/fix is quite easy thought:

```c++
NanThrowError((v8::Handle<v8::Value>) err);
```

**Comment by bnoordhuis** [comment]
I speculate you're hitting a compiler bug.  Two `NanThrowError` overloads exist, one for `v8::Handle<v8::Value>` and one for `v8::Handle<v8::String>`, but they cannot conflict here: `v8::Object` is an instance of `v8::Value` but not `v8::String`, there is no ambiguity here.

I don't have any off-the-cuff suggestions on how to fix this in nan but what happens when you rewrite the call to `NanThrowError(err.As<v8::Value>())`?

**Comment by LinusU** [comment]
Yeah I thought it was strange, hmm.

Just published the fix I just posted, is there any benefit in doing `err.As<v8::Value>()` instead?

**Comment by bnoordhuis** [comment]
`.As<T>()` adds a bit more type-safety than a C style (or even C++ style) cast does.  Apart from that, they're identical.

**Comment by LinusU** [comment]
Cool, I guess that it's more idiomatic then :+1:

**Comment by kkoopa** [comment]
[The tests](https://github.com/nodejs/nan/blob/master/test/cpp/error.cpp) don't complain with our compilers.
