### ISSUE TITLE
Broken build on node 10.5.0

### ISSUE THREAD

**Issue by mattcollier** [nodejs/nan#793]
node: 10.5.0
npm: 6.1.0
Debian Stretch

The error reported is:
```
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
```

I see from looking at other issue here that `ForceSet` has been deprecated for a while and has finally been removed from V8.

Came upon this by way of https://github.com/kelektiv/node.bcrypt.js/releases/tag/v2.0.1

tracking: https://github.com/digitalbazaar/bedrock-authn-password/issues/21 https://github.com/kelektiv/node.bcrypt.js/issues/625

**Comment by kkoopa** [comment]
That was addressed with the release of 2.8.0 in November last year.
