### ISSUE TITLE
Node 7.7 broken

### ISSUE THREAD

**Issue by JoshuaWise** [nodejs/nan#644]
When I try to build [`better-sqlite3`](https://github.com/JoshuaWise/better-sqlite3) for node 7.7, I get this error:
```
In file included from ../node_modules/nan/nan.h:47:
/Users/josh/.node-gyp/7.7.0/include/node/node.h:44:10: fatal error: 
      'tracing/trace_event.h' file not found
```

It works fine in node 7.6

**Comment by kkoopa** [comment]
Never seen a tracing header. I think you should file a bug against node.js, or node-gyp. I believe there has been some reshuffling of files and directories. My theory is that no native modules can be built with Node 7.7.

**Comment by addaleax** [comment]
See https://github.com/nodejs/node/issues/11628, which is being fixed at https://github.com/nodejs/node/pull/11634

(tl;dr: It’s Node’s fault and 7.7.1 will be out with a fix soon)

**Comment by kkoopa** [comment]
Thanks for a quick response. I'll leave this issue up until I can remember to close it, so we hopefully don't get repeat filings.

**Comment by JoshuaWise** [comment]
Cool, thanks for the info.

**Comment by targos** [comment]
@kkoopa v7.7.1 is out
