### ISSUE TITLE
Build fails with -pedantic-errors set

### ISSUE THREAD

**Issue by ndob** [nodejs/nan#456]
I encountered this when upgrading [duktape-node](https://github.com/ndob/duktape-node)  (in which I had -pedantic-errors flag set for compilation) to use nan 2.0.9. All problems seem to be related to reinterpret_casts introduced in commit 11902dade135c409d21f0d9de051f3dedb319068.

 This happens at least with g++ version 4.8.4.

Basically there are a lot of this kind of errors:

```shell
../../nan.h:2049:59: error: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Werror=pedantic]
       , New<v8::External>(reinterpret_cast<void *>(deleter)));
```

You can reproduce this problem by adding -pedantic-erros to cflags-property in test/binding.gyp.

**Comment by kkoopa** [comment]
Remove the flag.
