### ISSUE TITLE
Electron-rebuild canvas fails with nan 2.14.1, works with 2.14.0

### ISSUE THREAD

**Issue by inDigiNeous** [nodejs/nan#892]
Hey, I had trouble trying to figure out why running

```
npx electron-rebuild canvas
```

Failed with the following error on Windows 10 x64:

```
Canvas.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)
```

I reported the issue to to the node-canvas repository here: https://github.com/Automattic/node-canvas/issues/1589

With more detail about the issue.
Somebody figured out nan 2.14.1 was the culprit, downgrading manually to nan 2.14.0 with

```
npm install nan@2.14.0
```

Fixed the compilation.

**Comment by bnoordhuis** [comment]
The change in v2.14.1 that is responsible is 2c023bd447661a61071da318b0ff4003c3858d39.

You mention in the other issue that you're using electron 8.2.0. https://github.com/electron/releases claims it's shipping V8 8.0.426.27-electron.0 and that version supports the new API (it was added in 8.0.)

On the other hand... it also claims it's shipping Node.js v12.13.0 and that version of Node bundles V8 7.7 but I know electron probably does a frankenbuild of Node.js so I guess either is possible.

My hunch is that this is not a nan issue. It could be an electron issue per the above. At the very least, the development headers that electron ships claim it's V8 8.0 because that's what nan feature-gates on.

**Comment by mauricedoepke** [comment]
Had the same issue with nodejs 14 and electron 11.
Both claim to use v8 >= 8.

I manually edited the file from the commit 2c023bd in "./node_modules/canvas/node_modules/nan/nan_typedarray_contents.h"
to use the old api. That made it working for me.

**Comment by TanninOne** [comment]
I'm pretty sure this is an error in how electron is built for windows, I have created a bug report here: https://github.com/electron/electron/issues/29893
Going back to nan 2.14.0 won't work if you want to build for electron 13 or later as the old api got removed.

**Comment by wxfred** [comment]
@TanninOne Is there any workaround?

**Comment by TanninOne** [comment]
@wxfred tl;dr: So the solution currently would be to build modules with clang, which, to be completely honest, is a massive pita on windows atm.

Contrary to what I said earlier this isn't because of a bug in electron but because electron is built with clang now, which uses libc++ for its implementation of the stl.
If you build your native module with msvc or gcc, they will (by default) use their own implementation of the stl which isn't binary compatible which could then lead to crashes at runtime.
To avoid this libc++ changes the exported name of affected functions (adding a namespace called __1) which means the error happens at linktime instead of runtime.

The solution would be to build your native module with libc++, same as electron itself, but afaik the stl implementation is tightly tied with the compiler so you probably can't just use msvc with libc++, you have to use the compiler it's intended for.

node-gyp for example unfortunately isn't designed to let you use clang on windows.

This is where I am atm, I haven't yet managed to build my modules with clang and I'd rather make the switch to napi instead, seems like a better use of the time long term (plus I'd rather code than fight build systems)

**Comment by Sakari369** [comment]
This is still an issue, when building node-canvas with electron-rebuild. Now faced this problem when installed electron 11.4.10, had to downgrade to nan 2.14.0 manually to fix the build.

**Comment by devyetii** [comment]
Problem still here on Electron v16.0.1 with canvas 2.8.0 and nan 2.15.0 on Windows 10 (Here's the full thing [https://github.com/electron/electron-rebuild/issues/924](original issue). Still showing the main error mentioned in this issue's body by @Sakari369. Really frustrated having to deal with all this hassle while only wanting to code a simple app using canvas.

**Comment by GitMurf** [comment]
> Problem still here on Electron v16.0.1 with canvas 2.8.0 and nan 2.15.0 on Windows 10 (Here's the full thing [original issue](https://github.com/electron/electron-rebuild/issues/924). Still showing the main error mentioned in this issue's body by @Sakari369. Really frustrated having to deal with all this hassle while only wanting to code a simple app using canvas.

@devyetii I am having the same issue and have been troubleshooting for weeks now without able to figure out any workaround. Did you ever find a solution to this? So frustrating!

**Comment by GitMurf** [comment]
This can now be closed with 🎉 https://github.com/Automattic/node-canvas/pull/2235

**Comment by Sakari369** [comment]
> I wanted to look into this issue, but apparently it is fixed now? @Sakari369 could you please confirm

 Will take a look as soon as I'm looking into the build process of my sw yet again, might take a while ..

**Comment by StefanStojanovic** [comment]
@Sakari369 did you get a chance to check this?

**Comment by Sakari369** [comment]
> @Sakari369 did you get a chance to check this?

Hey! I did get this to work on Windows with Electron version 24.8.8, but that's as far as I had the bravery to update my Electron framework to, so not sure about newer versions.  

But alas, I do not even know why it started working suddenly. And I don't have my Windows VM here right now, so I can't even check the configuration. I just remember being frustrated to having to battle this again, due to having to update my app and Electron framework, and just being almost close to giving up, then suddenly the thing compiled. 

But that's all I can share .. don't have my Windows VM disk here right now, it's on a separate machine. Although dont think that would help, I seriously don't know what fixed it :P  

I do know and have followed the conversation on the actual node-canvas repository, that they are close to releasing version 3, it might have fixed the building ?

**Comment by StefanStojanovic** [comment]
Thanks for the detailed answer. Since, from what I understood from your message, this is fixed now, I'd suggest closing the issue. If you notice it happening again you can always reopen it, or open a new one and reference this one in it.
