### ISSUE TITLE
2.9.1 errors at npm install

### ISSUE THREAD

**Issue by quentin-sommer** [nodejs/nan#736]
Here's the output. Working on 2.8.0

Not sure if I can be of any help let me know if I can provide more info!

node: 8.1.4
npm: 5.0.3
os: macOS 10.12.6
```
/Users/sommerq/work/lol/node_modules/nan/nan.h:1359:11: error: no type named 'async_context' in namespace 'node'
    node::async_context context;
    ~~~~~~^
/Users/sommerq/work/lol/node_modules/nan/nan.h:1290:60: error: too few arguments to function call, expected 4, have 3
      context = node::EmitAsyncInit(isolate, resource, name);
                ~~~~~~~~~~~~~~~~~~~                        ^
node/v8.1.4/include/node.h:543:13: note: 'EmitAsyncInit' declared here
NODE_EXTERN async_uid EmitAsyncInit(v8::Isolate* isolate,
            ^
In file included from ../src/api/tools/v8Tools.cpp:1:
In file included from ../src/api/tools/v8Tools.h:5:
/Users/sommerq/work/lol/node_modules/nan/nan.h:1306:67: error: too few arguments to function call, expected 4, have 3
      context = node::EmitAsyncInit(isolate, resource, name_string);
                ~~~~~~~~~~~~~~~~~~~                               ^
node/v8.1.4/include/node.h:543:13: note: 'EmitAsyncInit' declared here
NODE_EXTERN async_uid EmitAsyncInit(v8::Isolate* isolate,
            ^
In file included from ../src/api/tools/v8Tools.cpp:1:
In file included from ../src/api/tools/v8Tools.h:5:
/Users/sommerq/work/lol/node_modules/nan/nan.h:1359:25: warning: private field 'context' is not used [-Wunused-private-field]
    node::async_context context;
                        ^
```

**Comment by etherElric** [comment]
We have the same issue on Mac only

**Comment by quentin-sommer** [comment]
Can confirm it's happening on mac

**Comment by kkoopa** [comment]
Duplicate of #235 subscribe to that issue instead.
