### ISSUE TITLE
support for electron 32

### ISSUE THREAD

**Issue by steinmetz85** [nodejs/nan#973]
With electron 32.0.1 and its underlying v8 version 12.8, there are mulitple errors when building NAN modules:

nan.h(700,39): error C2039: "IdleNotificationDeadline" ist kein Member von "v8::Isolate"
nan.h(2560,8): error C2039: "SetAccessor" ist kein Member von "v8::ObjectTemplate"
nan.h(2654,15): error C2039: "SetAccessor" ist kein Member von "v8::Object"
nan.h(2730,56): error C2440: "<function-style-cast>": "initializer list" kann nicht in "v8::NamedPropertyHandlerConfiguration" konvertiert werden
nan_scriptorigin.h(19,1): error C2664: "v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)" : Konvertierung von Argument 1 von "v8::Isolate *" in "v8::Local<v8::Value>" nicht möglich

**Comment by agracio** [comment]
In Electron v31 the following lines appeared as warnings

```
node_modules\nan\nan.h(700,39): warning C4996: 'v8::Isolate::IdleNotificationDeadline' : Use MemoryPressureNotification() to influence the GC schedule. 
node_modules\nan\nan.h(2654,15): warning C4996: 'v8::Object::SetAccessor': Use SetNativeDataProperty instead 
node_modules\nan\nan.h(2730,56): warning C4996: 'v8::NamedPropertyHandlerConfiguration ::NamedPropertyHandlerConfiguration': Provide interceptor callbacks with new signatures instead (NamedPropertyXxxCallback)
node_modules\nan\nan_scriptorigin.h(19,23): warning C4996: 'v8::ScriptOrigin::ScriptOrigin': Use constructor without the isolate. 
node_modules\nan\nan_scriptorigin.h(23,23): warning C4996: 'v8::ScriptOrigin::ScriptOrigin': Use constructor without the isolate. 
node_modules\nan\nan_scriptorigin.h(30,23): warning C4996: 'v8::ScriptOrigin::ScriptOrigin': Use constructor without the isolate. 

```

In Electron v32  it now throws these errors:

```
node_modules\nan\nan.h(700,39): error C2039: 'IdleNotificationDeadline': is not a member of 'v8::Isolate' 
node_modules\nan\nan.h(2560,8): error C2039: 'SetAccessor': is not a member of 'v8::ObjectTemplate' 
node_modules\nan\nan.h(2608,8): error C2039: 'SetAccessor': is not a member of 'v8::ObjectTemplate'
node_modules\nan\nan.h(2654,15): error C2039: 'SetAccessor': is not a member of 'v8::Object' 
node_modules\nan\nan.h(2730,56): error C2440: '<function-style-cast>': cannot convert
from 'initializer list' to 'v8::NamedPropertyHandlerConfiguration'
node_modules\nan\nan.h(2800,58): error C2440: '<function-style-cast>': cannot convert
from 'initializer list' to 'v8::IndexedPropertyHandlerConfiguration'

node_modules\nan\nan_scriptorigin.h(19,23): error C2664: 'v8::ScriptOrigin::ScriptOrig in(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Value>' 
node_modules\nan\nan_scriptorigin.h(23,23): error C2664: 'v8::ScriptOrigin::ScriptOrig in(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Value>' 
node_modules\nan\nan_scriptorigin.h(30,23): error C2664: 'v8::ScriptOrigin::ScriptOrig in(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Value>' 


```

**Comment by kkoopa** [comment]
Based on https://github.com/v8/v8/commit/6ec883986bd417e2a42ddb960bd9449deb7e4639 since V8 12.5.59  there is a need to use the `Local<Name>` version of `SetAccessor` instead. `IdleNotificationDeadline` is deprecated with no replacement since V8 11.3.218 and removed in https://github.com/v8/v8/commit/c8c168f06432e1dd9d47eae9a659c40f64d10a78 V8 12.7.41.

**Comment by agracio** [comment]
Could this used be to replace `IdleNotificationDeadline` in a different part of the code?

```
node_modules\nan\nan.h(700,39): warning C4996: 'v8::Isolate::IdleNotificationDeadline' : Use MemoryPressureNotification() to influence the GC schedule. 
```

**Comment by kkoopa** [comment]
Based on some comments in linked commits, MemoryPressurrNotification seems to correspond more to some GCLimit-ish-named thing not exposed by NAN. I do not see a straight replacement for this, so it will just be deprecated deplaced by a no-op.

**Comment by kkoopa** [comment]
I created an untested PR that should deal with this. Please try it out.

**Comment by agracio** [comment]
I am getting this error
```
node_modules\nan\nan.h(2567,138): error C1012: unmatched parenthesis: missing ')'
```

**Comment by kkoopa** [comment]
Thanks for reporting, I have updated the PR.

**Comment by agracio** [comment]
Ok this one is on me, instead of just building your branch of `nan` and finding all the errors encountered on build I should have changed the files in my projects node_modules/nan

```
node_modules\nan\nan.h(2673,15): error C2664: 'v8::Maybe<bool> v8::Object::SetNativeDa taProperty(v8::Local<v8::Context>,v8::Local<v8::Name>,v8::AccessorNameGetterCallback,v8::AccessorNameSetterCallback,v8::Lo cal<v8::Value>,v8::PropertyAttribute,v8::SideEffectType,v8::SideEffectType)': cannot convert argument 6 from 'v8::AccessCo ntrol' to 'v8::PropertyAttribute' 
node_modules\nan\nan.h(2752,56): error C2440: '<function-style-cast>': cannot convertfrom 'initializer list' to 'v8::NamedPropertyHandlerConfiguration'
node_modules\nan\nan.h(2822,58): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'v8::IndexedPropertyHandlerConfiguration' 
```

**Comment by kkoopa** [comment]
Alright, so `v8::AccessControl` has been removed. This requires a long dance of deprecating and splitting out functions with default arguments to overloads in order to remove the argument from `Nan::SetAccessor`. It is doable, but tedious. I do not see what is wrong with the Property Handler Configurations, they are supposed to correspond to [this constructor](https://github.com/v8/v8/blob/12.9.171/include/v8-template.h#L785).

**Comment by agracio** [comment]
After the fix now getting even more very strange errors 

```
nan_callbacks_12_inl.h(277,34): error C2039: 'Get': is not a member o f 'Nan::ReturnValue<T>' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(277,34): error C2039:         with [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(277,34): error C2039:         [ [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(277,34): error C2039:             T=v8::Value [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(277,34): error C2039:         ] [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(322,34): error C2039: 'Get': is not a member of 'Nan::ReturnValue<T>' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(322,34): error C2039:         with [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(322,34): error C2039:         [ [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(322,34): error C2039:             T=v8::Value [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(322,34): error C2039:         ] [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(387,34): error C2039: 'Get': is not a member of 'Nan::ReturnValue<T>' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(387,34): error C2039:         with [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(387,34): error C2039:         [ [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(387,34): error C2039:             T=v8::Boolean [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(387,34): error C2039:         ] [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(431,34): error C2039: 'Get': is not a member of 'Nan::ReturnValue<T>' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(431,34): error C2039:         with [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(431,34): error C2039:         [ [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(431,34): error C2039:             T=v8::Integer [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(431,34): error C2039:         ] [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(562,34): error C2039: 'Get': is not a member of 'Nan::ReturnValue<T>' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(562,34): error C2039:         with [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(562,34): error C2039:         [ [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(562,34): error C2039:             T=v8::Value [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(562,34): error C2039:         ] [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(606,34): error C2039: 'Get': is not a member of 'Nan::ReturnValue<T>' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(606,34): error C2039:         with [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(606,34): error C2039:         [ [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(606,34): error C2039:             T=v8::Value [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(606,34): error C2039:         ] [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(671,34): error C2039: 'Get': is not a member of 'Nan::ReturnValue<T>' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(671,34): error C2039:         with [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(671,34): error C2039:         [ [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(671,34): error C2039:             T=v8::Boolea n [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(671,34): error C2039:         ] [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(713,34): error C2039: 'Get': is not a member of 'Nan::ReturnValue<T>' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(713,34): error C2039:         with [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(713,34): error C2039:         [ [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(713,34): error C2039:             T=v8::Integer [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan_callbacks_12_inl.h(713,34): error C2039:         ] [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan.h(2717,30): error C2072: 'deleter_': initialization of a function  [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan.h(2759,33): error C2065: 'deleter_': undeclared identifier [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
nan.h(2828,58): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'v8::IndexedPropertyHandlerConfiguration' [C:\path\electron-edge-js\build\edge_coreclr.vcxproj]
```

**Comment by agracio** [comment]
Well here is a new list of errors

```
nan_callbacks_12_inl.h(19,35): error C7568: argument list missing after assumed function template 'ReturnValue' 
nan_callbacks_12_inl.h(19,29): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int 
nan_callbacks_12_inl.h(19,35): error C2144: syntax error: 'unknown-type' should be preceded by ')' 
nan_callbacks_12_inl.h(19,35): error C2144: syntax error: 'unknown-type' should be preceded by ';' 
nan_callbacks_12_inl.h(19,53): error C2059: syntax error: ')' 
nan_callbacks_12_inl.h(19,54): error C2988: unrecognizable template declaration/definition 
nan_callbacks_12_inl.h(19,54): error C2143: syntax error: missing ';'  before '<end Parse>' 
nan_callbacks_12_inl.h(20,1): error C2988: unrecognizable template de claration/definition 
nan_callbacks_12_inl.h(20,1): error C2059: syntax error: '}' 
nan_callbacks_12_inl.h(20,1): error C2143: syntax error: missing ';' before '}' 
nan_callbacks_12_inl.h(122,10): error C2977: 'Nan::imp::ReturnValue':  too many template arguments 
nan_callbacks_12_inl.h(122,25): error C2955: 'Nan::imp::ReturnValue':  use of class template requires template argument list 
nan_callbacks_12_inl.h(122,25): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(168,10): error C2977: 'Nan::imp::ReturnValue':  too many template arguments 
nan_callbacks_12_inl.h(168,25): error C2955: 'Nan::imp::ReturnValue':  use of class template requires template argument list 
nan_callbacks_12_inl.h(168,25): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(285,42): error C2977: 'Nan::imp::ReturnValue':  too many template arguments 
nan_callbacks_12_inl.h(285,58): error C2955: 'Nan::imp::ReturnValue':  use of class template requires template argument list 
nan_callbacks_12_inl.h(286,13): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(300,39): error C2664: 'void (v8::Local<v8::Str ing>,const Nan::PropertyCallbackInfo<v8::Value> &)': cannot convert argument 2 from 'Nan::imp::PropertyCallbackInfo<v8::Va lue>' to 'const Nan::PropertyCallbackInfo<v8::Value> &'  nan_callbacks_12_inl.h(301,37): error C2027: use of undefined type 'N an::imp::ReturnValue' 
nan_callbacks_12_inl.h(301,15): error C2672: 'Nan::imp::imp::GetReturnValue': no matching overloaded function found 
nan_callbacks_12_inl.h(345,46): error C2664: 'void (v8::Local<v8::String>,v8::Local<v8::Value>,const Nan::PropertyCallbackInfo<v8::Value> &)': cannot convert argument 3 from 'Nan::imp::Proper tyCallbackInfo<v8::Value>' to 'const Nan::PropertyCallbackInfo<v8::Value> &' 
nan_callbacks_12_inl.h(346,37): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(346,15): error C2672: 'Nan::imp::imp::GetReturnValue': no matching overloaded function found 
nan_callbacks_12_inl.h(388,12): error C2664: 'void (const Nan::PropertyCallbackInfo<v8::Array> &)': cannot convert argument 1 from 'Nan::imp::PropertyCallbackInfo<v8::Array>' to 'const Nan::P ropertyCallbackInfo<v8::Array> &' 
nan_callbacks_12_inl.h(410,39): error C2664: 'void (v8::Local<v8::String>,const Nan::PropertyCallbackInfo<v8::Boolean> &)': cannot convert argument 2 from 'Nan::imp::PropertyCallbackInfo<v8:: Boolean>' to 'const Nan::PropertyCallbackInfo<v8::Boolean> &' 
nan_callbacks_12_inl.h(411,37): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(411,15): error C2672: 'Nan::imp::imp::GetReturnValue': no matching overloaded function found 
nan_callbacks_12_inl.h(454,39): error C2664: 'void (v8::Local<v8::String>,const Nan::PropertyCallbackInfo<v8::Integer> &)': cannot convert argument 2 from 'Nan::imp::PropertyCallbackInfo<v8:: Integer>' to 'const Nan::PropertyCallbackInfo<v8::Integer> &' 
nan_callbacks_12_inl.h(455,37): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(455,15): error C2672: 'Nan::imp::imp::GetReturnValue': no matching overloaded function found 
nan_callbacks_12_inl.h(585,19): error C2664: 'void (uint32_t,const Nan::PropertyCallbackInfo<v8::Value> &)': cannot convert argument 2 from 'Nan::imp::PropertyCallbackInfo<v8::Value>' to 'con st Nan::PropertyCallbackInfo<v8::Value> &' 
nan_callbacks_12_inl.h(586,37): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(586,15): error C2672: 'Nan::imp::imp::GetReturnValue': no matching overloaded function found 
nan_callbacks_12_inl.h(629,26): error C2664: 'void (uint32_t,v8::Local<v8::Value>,const Nan::PropertyCallbackInfo<v8::Value> &)': cannot convert argument 3 from 'Nan::imp::PropertyCallbackInf o<v8::Value>' to 'const Nan::PropertyCallbackInfo<v8::Value> &' 
nan_callbacks_12_inl.h(630,37): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(630,15): error C2672: 'Nan::imp::imp::GetReturnValue': no matching overloaded function found 
nan_callbacks_12_inl.h(673,12): error C2664: 'void (const Nan::PropertyCallbackInfo<v8::Array> &)': cannot convert argument 1 from 'Nan::imp::PropertyCallbackInfo<v8::Array>' to 'const Nan::P ropertyCallbackInfo<v8::Array> &' 
nan_callbacks_12_inl.h(694,19): error C2664: 'void (uint32_t,const Nan::PropertyCallbackInfo<v8::Boolean> &)': cannot convert argument 2 from 'Nan::imp::PropertyCallbackInfo<v8::Boolean>' to 'const Nan::PropertyCallbackInfo<v8::Boolean> &' 
nan_callbacks_12_inl.h(695,37): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(695,15): error C2672: 'Nan::imp::imp::GetReturnValue': no matching overloaded function found 
nan_callbacks_12_inl.h(736,19): error C2664: 'void (uint32_t,const Nan::PropertyCallbackInfo<v8::Integer> &)': cannot convert argument 2 from 'Nan::imp::PropertyCallbackInfo<v8::Integer>' to 'const Nan::PropertyCallbackInfo<v8::Integer> &' 
nan_callbacks_12_inl.h(737,37): error C2027: use of undefined type 'Nan::imp::ReturnValue' 
nan_callbacks_12_inl.h(737,15): error C2672: 'Nan::imp::imp::GetReturnValue': no matching overloaded function found 
nan_new.h(21,15): error C2039: 'To': is not a member of 'Nan' 
nan_new.h(21,22): error C2275: 'v8::Integer': expected an expression instead of a type 
nan_new.h(21,34): error C2039: 'ToLocalChecked': is not a member of ' v8::Local<v8::Integer>' 
nan_new.h(28,15): error C2039: 'To': is not a member of 'Nan' 
nan_new.h(28,22): error C2275: 'v8::Int32': expected an expression instead of a type 
nan_new.h(28,32): error C2039: 'ToLocalChecked': is not a member of ' v8::Local<v8::Integer>' 
nan_new.h(35,15): error C2039: 'To': is not a member of 'Nan' 
nan_new.h(35,22): error C2275: 'v8::Uint32': expected an expression instead of a type 
nan_new.h(35,22): error C1003: error count exceeds 100; stopping compilation 
```

**Comment by kkoopa** [comment]
The friend declaration was not correct. Now it should compile.

**Comment by kkoopa** [comment]
Great. It is moving in the right direction. I noticed that the signature of property setters had changed further, so I made another update.

**Comment by agracio** [comment]
Getting closer

```
nan_callbacks_12_inl.h(344,13): error C2664: 'Nan::PropertyCallbackIn fo<v8::Value>::PropertyCallbackInfo(const v8::PropertyCallbackInfo<v8::Value> &,const v8::Local<v8::Value>)': cannot convert argument 1 from 'const v8::PropertyCallbackInfo<void>' to 'const v8::PropertyCallbackInfo<v8::Value> &' 
nan_callbacks_12_inl.h(628,13): error C2664: 'Nan::PropertyCallbackIn fo<v8::Value>::PropertyCallbackInfo(const v8::PropertyCallbackInfo<v8::Value> &,const v8::Local<v8::Value>)': cannot convert argument 1 from 'const v8::PropertyCallbackInfo<void>' to 'const v8::PropertyCallbackInfo<v8::Value> &' 
```

**Comment by kkoopa** [comment]
That is unfortunate. I cannot think of a reasonable way of taking a `v8::PropertyCallbackInfo<void>` and somehow making a`Nan::PropertyCallbackInfo<v8::Value>`. Hence, this seems to require breaking the signature of property setter callbacks, but I cannot make them compatible for all supported versions. Unless someone can come up with a solution, I guess this is it.

**Comment by agracio** [comment]
> I guess this is it.

You mean there isnt a way for nan to support Electron 32+ or anything based on newer versions of v8?

**Comment by kkoopa** [comment]
Unfortunately, that is how it appears. It might not be the final answer, but I cannot think of a solution for papering over this change.

**Comment by agracio** [comment]
I understand that this appears to be an issue that cannot be dealt easily but should nan users expect any long term plan for Electron 32+ support? 
Unlike Node.js Electron does not offer long term support for its versions and in about 6 or even less months v32 will become the last supported version with release of v33 and v34.
And this issue is likely not only limited to Electron but to other apps that will slowly migrate to newer versions of v8.

**Comment by kkoopa** [comment]
The goal of this project has always been to provide backwards compatibility by providing a consistent API across all versions. I have wondered for the past ten years when a breaking change would come. The [cause for this change in V8](https://issues.chromium.org/issues/348660658) is compliance with the ECMAScript standard, changing the underlying semantics. Last time a big break came was whatever V8 version came with Node 4.3, which added the optionals (Maybe<T>, MaybeLocal<T>), but that could still be shoehorned in to the older versions. The difference here is that I do not see a clear way of making the callback signatures work backwards. The internals of V8 are locked down through private access modifiers, making it nigh impossible to do many of the required behind-the-scenes operations when trying to modify its behavior from the outside.

Now, supposing that this last issue with the callbacks could be resolved, it would also be necessary to detect if the callback has thrown an exception and account for that when returning the boolean indicating whether the interceptor did anything. There might be more gotchas hiding in the rough. I have not looked into the feasibility of this.

**Comment by agracio** [comment]
So if I understand it correctly you saying there are no plans to add support for newer v8 versions in any foreseeable future?

**Comment by agnat** [comment]
*Plonk.*

>  should nan users expect any long term plan for Electron 32+ support?

This is a common misconception. We don't support electron. If you look at the [README](https://github.com/nodejs/nan/blob/main/README.md) electron isn't mentioned anywhere. It's the other way around: Electron promises compatibility with node.js ... and breaks that promise on a regular basis. This is also why, from our perspective,  projects like electron, some call them franken-builds, are a bit of a nuisance.

Anyway, on a quick glance I agree with @kkoopa. This looks like an upcoming breaking change. NAN 3.0 ... finally... yay? 

> And this issue is likely not only limited to Electron but to other apps that will slowly migrate to newer versions of v8.

... and when that happens I'm sure we will take another stab at it. 😁

**Comment by steinmetz85** [comment]
Thanks to everyone for the work! 
Just to repeat it: It is not a problem with electron, but with v8 12.8+. electron is an early bird using v8 versions, but it has nothing to do with electron. So it doesn't matter, if you like it or not :-)
I understand, that you try to support older versions, but this is not a "forever" concept. There will be breaking changes from time to time. And upcoming versions of node.js will have the same problem.

**Comment by agracio** [comment]
@steinmetz85 I think it was not the case of Electron being an early adopter but rather that Chromium v128 was shipping with v8 12.8, but I might be entirely wrong.

It appears that v8 12.8 was added to main Node.js branch a couple of weeks ago so fingers crossed for Node.js v23 **nan** support or maybe even earlier while v23 pre-release undergoing testing.

**Comment by agracio** [comment]
First of all wanted to say that I do appreciate the work, very quick responses and attempts to fix the error from everyone, in my previous posts I was rather frustrated that the problem is being ignored since `nan` only covers Node.js and other projects are left to fend for themselves.

Now that v8 12.8 was merged into main Node.js branch 23.0.0 I tested on a different project that does not depend on Electron and unfortunately getting exact same errors. 

Initially getting the same errors as with Electron build and after applying patch from `new_breakage` branch it is back to 
```
nan_callbacks_12_inl.h(344,13): error C2664: 'Nan::PropertyCallbackInfo<v8::Value>::PropertyCallbackInfo(const v8::PropertyCallbackInfo<v8::Value> &,const v8::Local<v8::Value>)': cannot convert argument 1 from 'const v8::PropertyCallbackInfo<void>' to 'const v8::PropertyCallbackInfo<v8::Value> &' 
nan_callbacks_12_inl.h(628,13): error C2664: 'Nan::PropertyCallbackInfo<v8::Value>::PropertyCallbackInfo(const v8::PropertyCallbackInfo<v8::Value> &,const v8::Local<v8::Value>)': cannot convert argument 1 from 'const v8::PropertyCallbackInfo<void>' to 'const v8::PropertyCallbackInfo<v8::Value> &' 
```

> And this issue is likely not only limited to Electron but to other apps that will slowly migrate to newer versions of v8.
> ... and when that happens I'm sure we will take another stab at it.😁

Node.js 23 release is a couple months away so while it does not require urgent attention perhaps there should be some plans to address it.

**Comment by bugsounet** [comment]
@toshiyuki-rs 's electron v32 support works :)

tested on electron v32.1.2
nice !

**Comment by danielweck** [comment]
> @toshiyuki-rs 's electron v32 support works :)

Yes :)
My native module for Electron 32.1.2 builds fine with my own patches, but I much prefer this fork:

https://github.com/oc-soft/npm-nan/compare/4d1d74e0a9ea8fa8091b88e45dc57e4c7eb9cdf7...6c6e8aa4165384a1bf944c7ebc0f7cca5ced7bf0

I install the regular NAN distribution from NPM:

https://www.npmjs.com/package/nan/v/2.20.0

...but I create a patch and apply it via `postinstall`:

* `git diff -p 4d1d74e0a9ea8fa8091b88e45dc57e4c7eb9cdf7 6c6e8aa4165384a1bf944c7ebc0f7cca5ced7bf0 > nan-git-diff.patch`

* `git apply --verbose --no-index --directory=PATH/TO/node_modules/nan/ nan-git-diff.patch`

(in a Docker context without the root Git directory of your main project, simply remove `PATH/TO/` ... or use the `patch -p1` command instead of `git apply` ;) )

**Comment by agracio** [comment]
Tried it but `git diff -p 4d1d74e0a9ea8fa8091b88e45dc57e4c7eb9cdf7 6c6e8aa4165384a1bf944c7ebc0f7cca5ced7bf0 > nan-git-diff.patch` returns `fatal: bad object 4d1d74e0a9ea8fa8091b88e45dc57e4c7eb9cdf7`. 
Any ideas how to solve that?

**Comment by agracio** [comment]
Also works with upcoming Node.js 23 native libraries.

**Comment by steinmetz85** [comment]
@kkoopa Thanks for your work. But there is still something missing:

`nan.h(2618,8): error C2039: "SetAccessor" ist kein Member von "v8::ObjectTemplate"`

It might work with node 20.17.0 but not with v8 12.8 and therefor with node 23+

@toshiyuki-rs In your oc-soft repository there is an additional if before the SetAccessor definiton:
`#if defined(V8_MAJOR_VERSION) && \
    ((V8_MAJOR_VERSION) <= 6 && V8_MINOR_VERSION < 5)`

Is there a reason, why this isn't part of your pull request? Adding this if statement solves the problem for v8 12.8

**Comment by kkoopa** [comment]
I had originally done it like this: https://github.com/nodejs/nan/pull/974/commits/9fa23b764bf0863acf7267de2343a0429e37f742

**Comment by steinmetz85** [comment]
I can confirm that this works with electron 32

**Comment by danielweck** [comment]
Mhmm, unfortunately NAN `v2.21.0` fails with Electron `v32.2.0`:

```
../node_modules/nan/nan.h:2618:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
 2618 |   tpl->SetAccessor(
      |   ~~~~~^
../node_modules/nan/nan.h:2666:8: error: no member named 'SetAccessor' in 'v8::ObjectTemplate'
 2666 |   tpl->SetAccessor(
      |   ~~~~~^
../node_modules/nan/nan.h:2712:15: error: no member named 'SetAccessor' in 'v8::Object'
 2712 |   return obj->SetAccessor(
      |          ~~~~~^
```

**Comment by danielweck** [comment]
So, for now I will continue to use @toshiyuki-rs :

https://github.com/oc-soft/npm-nan/compare/4d1d74e0a9ea8fa8091b88e45dc57e4c7eb9cdf7...6c6e8aa4165384a1bf944c7ebc0f7cca5ced7bf0

...and I see new commits:

https://github.com/oc-soft/npm-nan/commits/main/

is this related?

https://github.com/nodejs/nan/pull/974

https://issues.chromium.org/issues/348660658

**Comment by danielweck** [comment]
Ah, Electron v33 is broken, unfortunately: https://github.com/nodejs/nan/issues/978

**Comment by agracio** [comment]
Electron 33 moved to v8 13 while Node.js main is currently on v8 12.9, perhaps someone can create a working branch that addresses the problem?
